const API_BASE = localStorage.getItem('LUDO_MASTER_API') || 'https://YOUR-RENDER-SERVICE.onrender.com';
let socket=null, currentMatch=null, adminKey=sessionStorage.getItem('LUDO_ADMIN_KEY')||'';
const ENTRIES=[50,30,60], WINS=[90,50,110];
function savePage(p){localStorage.setItem('LUDO_MASTER_PAGE',p)}
function show(page){savePage(page);const c=document.getElementById('content');
if(page==='home')c.innerHTML='<div class="card" style="text-align:center;padding:28px 18px"><h2>🎲 Ludo Master-এ সবাইকে স্বাগতম 🥰</h2><p>Real 1vs1 ম্যাচ খেলুন।</p></div><div class="card"><button class="action" onclick="show(\'matches\')">🎮 Matches দেখুন</button></div>';
if(page==='matches')c.innerHTML='<div class="card"><h2>🎮 Matches</h2><p class="small">Real-time 2 Player Match</p></div>'+ENTRIES.map((e,i)=>`<div class="card"><h3>1 vs 1 — Match ${i+1}</h3><p><b>Entry:</b> ৳${e}</p><p><b>Winning:</b> ৳${WINS[i]}</p><p id="m${i}" class="small">Loading...</p><button class="action" style="background:#FFD600;color:#111;font-weight:bold" onclick="joinMatch(${e},${WINS[i]})">Join</button></div>`).join('');loadMatches();}
if(page==='tournament')c.innerHTML='<div class="card"><h2>🏆 Tournament</h2><p>Coming soon</p></div>';
if(page==='wallet')c.innerHTML='<div class="card"><h2>💰 Wallet</h2><div class="balance">৳0.00</div></div><div class="card"><h3>Deposit</h3><p>bKash/Nagad: <b>01301470686</b></p><p class="small">Payment provider verification and backend processing should be connected before real-money use.</p></div>';
if(page==='profile')c.innerHTML='<div class="card"><h2>👤 Profile</h2><input id="playerName" placeholder="আপনার নাম" style="width:100%;padding:12px"><button class="action" onclick="saveName()">Save</button></div>';
if(page==='admin')renderAdmin();
}
function saveName(){localStorage.setItem('LUDO_MASTER_NAME',document.getElementById('playerName').value.trim()||'Player');alert('Name saved');}
async function api(path,opts={}){const r=await fetch(API_BASE+path,opts);if(!r.ok){let msg='Request failed';try{const x=await r.json();msg=x.error||msg}catch(e){}throw new Error(msg)}return r.json()}
async function loadMatches(){try{const data=await api('/api/matches');for(let i=0;i<3;i++){const m=data.find(x=>x.entry===ENTRIES[i]);const el=document.getElementById('m'+i);if(el)el.textContent=m?`${m.players.length}/2 Players${m.roomCode?' • Code available':''}`:'Ready to join';}}catch(e){document.querySelectorAll('[id^=m]').forEach(x=>x.textContent='Backend URL সেট করুন');}}
async function joinMatch(entry,winning){const name=localStorage.getItem('LUDO_MASTER_NAME')||prompt('আপনার নাম লিখুন')||'Player';localStorage.setItem('LUDO_MASTER_NAME',name);try{let data=await api('/api/matches');let m=data.find(x=>x.entry===entry&&x.winning===winning&&x.players.length<2&&x.status==='waiting');if(!m)m=await api('/api/matches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entry,winning})});currentMatch=m;connect(m.matchId,name);}catch(e){alert('Backend connection হয়নি: '+e.message);}}
function connect(matchId,name){if(socket)socket.disconnect();socket=io(API_BASE);socket.on('connect',()=>socket.emit('match:join',{matchId,name}));socket.on('match:update',renderMatch);socket.on('match:error',x=>alert(x.message||x));}
function renderMatch(m){currentMatch=m;document.getElementById('content').innerHTML=`<div class="card"><h2>🎮 Match ৳${m.entry}</h2><p><b>Players:</b> ${m.players.length}/2</p>${m.players.map(p=>`<p>👤 ${escapeHtml(p.name)}</p>`).join('')}${m.players.length===2?'<p>✅ Match Full — Admin এখন Start করতে পারবে</p>':''}${m.roomCode?`<div class="payment-number-box"><b>Ludo King Room Code</b><div id="roomCode" style="font-size:28px;font-weight:800;margin:10px">${escapeHtml(m.roomCode)}</div><button onclick="copyCode()">Copy Code</button></div>`:'<div class="payment-number-box"><b>Ludo King Room Code</b><p class="small">এখনো code দেওয়া হয়নি। Admin Ludo King থেকে আসল code এখানে প্রকাশ করবে।</p></div>'}</div><button class="action" onclick="show('matches')">← Matches</button>`}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function copyCode(){navigator.clipboard?.writeText(document.getElementById('roomCode').textContent).then(()=>alert('Code copied'))}
async function renderAdmin(){
const c=document.getElementById('content');
if(!adminKey){c.innerHTML='<div class="card"><h2>🔐 Admin Login</h2><p class="small">Render-এর ADMIN_KEY এখানে দিন। এটি শুধু এই ডিভাইসের session-এ থাকবে।</p><input id="adminKey" type="password" placeholder="Admin Key" style="width:100%;padding:12px;border:1px solid #ccc;border-radius:10px"><button class="action" onclick="loginAdmin()">Login</button></div>';return;}
try{const data=await api('/api/matches');c.innerHTML='<div class="card"><h2>🔐 Admin Panel</h2><p class="small">শুধু 2/2 হলে Start করুন। Room Code প্রথমে ফাঁকা থাকবে; Ludo King-এর আসল code লিখে Publish করুন।</p><button class="action" onclick="adminLogout()">Logout</button></div>'+ENTRIES.map((e,i)=>{const m=data.find(x=>x.entry===e);return `<div class="card"><h3>Match ${i+1} — ৳${e} → ৳${WINS[i]}</h3><p><b>Players:</b> ${m?m.players.length:0}/2</p><p><b>Status:</b> ${m?escapeHtml(m.status):'No match yet'}</p><p><b>Room Code:</b> ${m&&m.roomCode?escapeHtml(m.roomCode):'ফাঁকা'}</p>${m?`<button class="action" ${m.players.length!==2?'disabled':''} onclick="adminStart('${m.matchId}')">${m.players.length===2?'▶ Start':'⏳ 2 Players হলে Start'}</button>`:'<p class="small">কোনো active match নেই</p>'}</div>`}).join('');}
catch(e){adminKey='';sessionStorage.removeItem('LUDO_ADMIN_KEY');c.innerHTML='<div class="card"><p>Admin authentication failed.</p></div>';}}
function loginAdmin(){const v=document.getElementById('adminKey').value.trim();if(!v)return alert('Admin Key দিন');adminKey=v;sessionStorage.setItem('LUDO_ADMIN_KEY',v);renderAdmin();}
function adminLogout(){adminKey='';sessionStorage.removeItem('LUDO_ADMIN_KEY');renderAdmin();}
async function adminStart(matchId){
try{const data=await api('/api/matches');const m=data.find(x=>x.matchId===matchId);if(!m||m.players.length!==2)return alert('2 জন player join না করলে Start করা যাবে না।');
const code=prompt('Ludo King-এ room তৈরি করে আসল Room Code এখানে লিখুন।\nCode এখনো প্রকাশ হবে না যতক্ষণ Publish না করেন:','');if(code===null)return;if(!code.trim())return alert('Room Code ফাঁকা রাখা হয়েছে।');
await api('/api/matches/'+encodeURIComponent(matchId)+'/room',{method:'POST',headers:{'Content-Type':'application/json','x-admin-key':adminKey},body:JSON.stringify({roomCode:code.trim()})});alert('Room Code players-দের কাছে প্রকাশ করা হয়েছে।');renderAdmin();}
catch(e){if(/401|403|admin/i.test(e.message)){adminKey='';sessionStorage.removeItem('LUDO_ADMIN_KEY');}alert(e.message||'Publish failed');renderAdmin();}}
show(localStorage.getItem('LUDO_MASTER_PAGE')||'home');
